fix logs go to stderr for displaying

diff --git a/libexec/helpers b/libexec/helpers
--- a/libexec/helpers
+++ b/libexec/helpers
@@ -1,5 +1,9 @@
 #!/usr/bin/env bash
 
+function error_log() {
+  echo -e "tgenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
+}
+
 function error_and_die() {
   echo -e "tgenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
   exit 1
