Works after QA

diff --git a/libexec/tgenv-install b/libexec/tgenv-install
--- a/libexec/tgenv-install
+++ b/libexec/tgenv-install
@@ -2,6 +2,7 @@
 
 [ -n "${TGENV_DEBUG}" ] && set -x
 source "${TGENV_ROOT}/libexec/helpers"
+source "${TGENV_ROOT}/libexec/retry"
 
 [ "${#}" -gt 1 ] && error_and_die "usage: tgenv install [<version>]"
 
@@ -60,14 +61,19 @@ tarball_name="terragrunt_${os}";
 
 info "Installing Terragrunt v${version}"
 
-function install() {
+function install_tg_version() {
+  local http_code
   http_code=$(curlw -# --location-trusted -w "%{http_code}" -o "${dst_path}/terragrunt" "${version_url}/${tarball_name}")
-  curl_exit_code=$?
+  local curl_exit_code=$?
 
-  if [[ http_code =~ ^5 ]]; then
-    return 1 # fail
-  elif [[ http_code =~ ^4 ]]; then
+  if [[ $http_code =~ ^4 ]]; then
+    echo "Got $http_code http code, TG version is invalid"
     return 2 # do not retry
+  elif [[ $http_code =~ ^5 ]]; then
+    echo "Got $http_code http code"
+    return 1 # retry
+  elif [[ $curl_exit_code -ne 0 ]]; then
+    return 1 # retry
   else
     return 0 # success
   fi
@@ -77,7 +83,7 @@ function install() {
 mkdir -p "${dst_path}" || error_and_die "Failed to make directory ${dst_path}"
 
 info "Downloading release tarball from ${version_url}/${tarball_name}"
-retry -tries 5 -sleep 10 -stop-on-exit-code 2 install || error_and_die "Tarball download failed"
+retry -tries 5 -sleep 5 -stop-on-exit-code 2 install_tg_version || error_and_die "Tarball download failed"
 install_exist_code=$?
 
 if [ "$install_exist_code" -eq 0 ]; then
